name: "My First Workflow"
on: push

jobs:
  test-job:
    runs-on: "ubuntu-latest"
    steps:
    - name: "Checkout repo"
      uses: actions/checkout@v4

    - name: "Listing all files"
      run: ls -all
    
    - name: "Executing shell script"
      run: ./shell.sh
