name: "My First Workflow"
on: push

jobs:
  build-job:
    runs-on: "ubuntu-latest"
    steps:
    - name: "Checkout repo"
      uses: actions/checkout@v4

    - name: "Listing all files"
      run: ls -all
    
    - name: "Executing shell script"
      run: |
       chmod +x shell.sh
       ./shell.sh

  test-job:
    needs: "build-job"
    runs-on: "ubuntu-latest"
    steps:
    - name: "Testing phase"
      run: echo "This is in testing phase" >> abc.txt

    - name: "Uploading artifact"
      uses: actions/upload-artifact@v3
      with:
        name: "ABC file"
        path: abc.txt

  deploy-job:
    needs: [test-job]
    runs-on: "ubuntu-latest"
    steps:
    - name: "Deploy on ec2"
      run: echo "Deployment on ec2 instance"

    - name: "Downloading artifact"
      uses: actions/download-artifact@v3
      with:
        name: "ABC file"

    - name: "Checking files"
      run: ls -all
