name: "My First Workflow"
on: push

jobs:
  test-job:
    runs-on: "ubuntu-latest"
    steps:
    - name: "Checkout repo"
      uses: actions/checkout@v4
    
    - name: "Printing text"
      run: |
       echo "This is my first job"
       ls -all
       uptime
