name: "My First Workflow"
on: push

jobs:
  build-job:
    runs-on: "ubuntu-latest"
    steps:
    - name: "Checkout repo"
      uses: actions/checkout@v4

    - name: "Listing all files"
      run: ls -all
    
    - name: "Executing shell script"
      run: |
       chmod +x shell.sh
       ./shell.sh

  test-job:
    runs-on: "ubuntu-latest"
    steps:
    - name: "Testing phase"
      run: echo "This is in testing phase"

  deploy-job:
    runs-on: "ubuntu-latest"
    steps:
    - name: "Deploy on ec2"
      run: "Deployment on ec2 instance"
