name: "Matrix Comfiguration"
on: workflow_dispatch

jobs:
  deploy:
    strategy:
      max-parallel: 2
      matrix:
        os: [ "ubuntu-latest", "windows-latest" ]
        images: [ "hello-world" , "alpine" ]
        include:
        - images: "amd64/alpine"
          os: ubuntu-latest
        exclude:
        - images: "alpine"
          os: "windows-latest"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Running on ${{ matrix.os }}
        run: docker info

      - name: Running on ${{ matrix.images }}
        run: docker run ${{ matrix.images }}
