name: "Environment variables"

on:
  workflow_dispatch

env:
  docker_tag: my_docker_image
  image_name: nginx

jobs:
  docker:
    runs-on: "ubuntu-latest"
    steps:
    - name: "Build docker image"
      run: |
        echo "docker build -t "$docker_tag" ."
        echo "docker run -it $image_name"
        
  authentications:
    runs-on: "ubuntu-latest"
    steps:
    - name: "docker auth"
      run: echo "docker login --username ${{ vars.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}"
      
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: "ubuntu-latest"
    steps:
    - name: "Deploying docker image"
      run: docker run hello-world
