name: "Environment variables"

On:
  push

env:
  docker_tag: my_docker_image
  image_name: nginx

jobs:
  docker:
    runs-on: "ubuntu-latest"
    steps:
    - name: "Build docker image"
      runs: |
        echo "docker build -t "$docker_tag" .
        echo "docker run -it $image_name"
      
