name: "Workflok fliter"
on:
#  push:
#    branches:
#    - main
#    - "!feature/*"

  pull_request:
    branches:
    - main
    types:
    - opened
    - closed
    paths-ignore:
    - README.md

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
    - name: "Echo"
      run: echo "This is sample yml file"

  dummy:
    runs-on "ubuntu-latest"
    steps:
    - name: "dummy"
      run: echo "dummy test"
